name: "splunk-integration"

services:
  events-generator:
    image: wazuh/indexer-events-generator
    build:
      context: ../tools/events-generator
    # container_name: events-generator
    depends_on:
      wazuh.indexer:
        condition: service_healthy
    command: bash -c "python run.py -a wazuh.indexer"

  wazuh.indexer:
    image: opensearchproject/opensearch:2.12.0
    # container_name: wazuh.indexer
    depends_on:
      wazuh-certs-generator:
        condition: service_completed_successfully
    hostname: wazuh.indexer
    ports:
      - 9200:9200
    environment:
      - node.name=wazuh.indexer
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - plugins.security.ssl.http.enabled=true
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/wazuh.indexer.pem
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/wazuh.indexer.pem
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/wazuh.indexer-key.pem
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/wazuh.indexer-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/root-ca.pem
      - plugins.security.authcz.admin_dn="CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California, C=US"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: curl -sku admin:admin https://localhost:9200/_cat/health | grep -q docker-cluster
      start_period: 10s
      start_interval: 3s
    volumes:
      - data:/usr/share/opensearch/data
      - ./certs/wazuh.indexer.pem:/usr/share/opensearch/config/wazuh.indexer.pem
      - ./certs/wazuh.indexer-key.pem:/usr/share/opensearch/config/wazuh.indexer-key.pem
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem

  wazuh.dashboard:
    image: opensearchproject/opensearch-dashboards:2.12.0
    # container_name: wazuh.dashboard
    depends_on:
      - wazuh.indexer
    hostname: wazuh.dashboard
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://wazuh.indexer:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query

  wazuh-certs-generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    # container_name: wazuh-certs-generator
    entrypoint: sh -c "/entrypoint.sh; chown -R 1000:999 /certificates; chmod 740 /certificates; chmod 440 /certificates/*"
    volumes:
      - ./certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml


  # =================================
  # Splunk and Logstash
  # =================================
  # https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html

  generator:
    image: alpine/openssl:latest
    depends_on:
      wazuh-certs-generator:
        condition: service_completed_successfully
    volumes:
      - ./certs/:/certs/
    entrypoint: >
      sh -c "
        openssl req -x509 -newkey rsa:4096 -passout pass:abcd1234 -keyout /certs/splunk.key -out /certs/splunk.pem -days 365 -subj '/CN=Wazuh' &&
        cat /certs/splunk.pem /certs/splunk.key /certs/root-ca.pem > /certs/splunkhec.pem
      "
    # entrypoint: >
    #   sh -c "
    #     cat /certs/splunk.pem /certs/splunk-key.pem /certs/root-ca.pem > /sp_certs/splunkhec.pem &&
    #     cp /certs/splunk.pem /sp_certs/splunk.pem &&
    #     cp /certs/splunk-key.pem /sp_certs/splunk-key.pem
    #   "

  splunk:
    image: splunk/splunk:9.0.4
    volumes:
      - ./certs:/opt/splunk/etc/auth/custom
      - ../splunk/config/default.yml:/tmp/defaults/default.yml
      - ../splunk/config/indexes.conf:/opt/splunk/etc/system/local/indexes.conf
    depends_on:
      wazuh-certs-generator:
        condition: service_completed_successfully
    ports:
      - '8000:8000'
      - '8088:8088'
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_HTTP_ENABLESSL: 'true'
      # SPLUNK_HTTP_ENABLESSL_CERT: /opt/splunk/etc/auth/custom/splunk.pem
      # SPLUNK_HTTP_ENABLESSL_PRIVKEY: /opt/splunk/etc/auth/custom/splunk.key
      # SPLUNK_HTTP_ENABLESSL_PRIVKEY_PASSWORD: "abcd1234"
      # SPLUNK_HEC_TOKEN: "abcd1234"
      SPLUNK_PASSWORD: password
      SPLUNK_HOSTNAME: splunk
      SPLUNK_STANDALONE_URL: https://splunk:8080
  
  logstash:
    depends_on:
      splunk:
        condition: service_healthy
    image: logstash-oss:8.6.2
    # container_name: logstash
    build:
      context: ../elastic
    environment:
      LOG_LEVEL: info
      MONITORING_ENABLED: false
    volumes:
      - ../splunk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./certs/root-ca.pem:/usr/share/logstash/root-ca.pem
      # - sp_certs:/etc/certs/elastic
    command: logstash -f /usr/share/logstash/pipeline/indexer-to-splunk.conf

volumes:
  data:
  sp_certs:
