name: Build packages 4.x (on push)

# This workflow runs when any of the following occur:
# - when a pull request is created or updated that targets a branch starting with "4."

on:
  pull_request:
    branches:
      - 4.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-build-workflow:
    uses: ./.github/workflows/4_builderpackage_indexer.yml
    secrets: inherit
    with:
      id: ${{ github.ref }}
