run-name: Build ${{ inputs.system }} wazuh-indexer on ${{ inputs.architecture }} | ${{ inputs.id }}
name: Build Wazuh indexer (single)

# This workflow runs when any of the following occur:
# - Run from another worklow of GH API
# - Run manually
on:
  workflow_call:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      checksum:
        description: "Checksum ?"
        type: boolean
        default: false
      is_stage:
        description: "Is stage ?"
        type: boolean
        default: false
      system:
        description: "Package OS"
        type: string
        default: deb
      architecture:
        description: "Package architecture"
        type: string
        default: amd64
      id:
        description: "ID used to identify the workflow uniquely."
        type: string
        required: false

  workflow_dispatch:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      checksum:
        description: "Checksum ?"
        type: boolean
        default: false
      is_stage:
        description: "Is stage ?"
        type: boolean
        default: false
      system:
        description: "Package OS"
        type: choice
        options:
          - rpm
          - deb
        default: deb
      architecture:
        description: "Package architecture"
        type: choice
        options:
          - amd64
          - x86_64
        default: amd64
      id:
        description: "ID used to identify the workflow uniquely."
        type: string
        required: false

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    with:
      revision: ${{ inputs.revision }}
      checksum: ${{ inputs.checksum }}
      is_stage: ${{ inputs.is_stage }}
      distribution: '[ "${{ inputs.system }}" ]'
      upload: true
      # Architecture is always 'x64', which is the default value in ./build.yml
      # It is an input just for convenience and standardisation.
    secrets: inherit
